### ISSUE TITLE
could not set up rake db

### ISSUE THREAD

**Issue by uglycoyote** [evanw/rapt#14]
Hello,

Awesome project!  My 6-year old is having tons of fun creating levels in RAPT, it is really stoking his imagination.  I wished that the level editor had a couple more features, such as rectangular block filling and hollowing and the ability to select and copy room shapes.

 I tried following your instructions to build RAPT locally.

Rake v0.7
Ruby 2.0.0
Python 2.7.5
on a Macbook

The "python build.py release" went fine, as did the "bundle install"

The "rake db:setup" did not work for me, output is at the bottom.

I successfully started up the server after the failed rake command, but when I tried to create a user I got a ruby error page with some database problems which are likely a result of the rake db:setup command not having completed successfully.

I'm illiterate about ruby/rake so I don't have the first clue here, might be something simple.  From the output it looks like it's doing a bunch of things successfully and then for some reason does not recognize the "username" attribute.

Thanks

================
output:

/Library/Ruby/Gems/2.0.0/gems/rake-0.8.7/lib/rake/alt_system.rb:32:in `<module:AltSystem>': Use RbConfig instead of obsolete and deprecated Config.
/Library/Ruby/Gems/2.0.0/gems/rake-0.8.7/lib/rake/alt_system.rb:32:in `<module:AltSystem>': Use RbConfig instead of obsolete and deprecated Config.
/Library/Ruby/Gems/2.0.0/gems/rake-0.8.7/lib/rake.rb:960:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
/Library/Ruby/Gems/2.0.0/gems/rake-0.8.7/lib/rake.rb:962:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
/Library/Ruby/Gems/2.0.0/gems/rake-0.8.7/lib/rake.rb:965:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
/Library/Ruby/Gems/2.0.0/gems/rake-0.8.7/lib/rake.rb:966:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
(in /Users/mike/rapt/rails)
[DEVISE] From version 1.2, there is no need to set your encryptor to bcrypt since encryptors are only enabled if you include :encryptable in your models. To update your app, please:

1) Remove config.encryptor from your initializer;
2) Add t.encryptable to your old migrations;
3) [Optional] Remove password_salt in a new recent migration. Bcrypt does not require it anymore.
-- create_table("levels", {:force=>true})
   -> 0.0052s
-- create_table("statistics", {:force=>true})
   -> 0.0015s
-- create_table("users", {:force=>true})
   -> 0.0203s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true})
   -> 0.0009s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true})
   -> 0.0010s
-- add_index("users", ["username"], {:name=>"index_users_on_username", :unique=>true})
   -> 0.0010s
-- initialize_schema_migrations_table()
   -> 0.0022s
-- assume_migrated_upto_version(20120101002338, "db/migrate")
   -> 0.0066s
rake aborted!
unknown attribute: username

**Comment by evanw** [comment]
Cool! I'm glad your son's having fun with it, and thanks for trying to get it running. Unfortunately it's a pretty old university project and it's bit-rotted since we made it. We developed this on ruby <2.0 and there's a backwards-compatibility bug that was introduced with ruby 2.0. Someone else was able to get rapt running using an older version of ruby (see issue #11). We're working on upgrading stuff to fix bit-rot but it's not working yet (see issue #12).
